"""empty message

Revision ID: 5cb32a74825e
Revises: 63871cdbd5b8
Create Date: 2023-04-27 11:13:03.233296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb32a74825e'
down_revision = '63871cdbd5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
